package:
  name: tensorflow
  version: "1.15.4"

build:
  number: 1
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    - python
    - pip
    - numpy >=1.8.2
    - six >=1.10.5
    - wheel >=0.26
    - protobuf
  run:
    - python
    - numpy >=1.8.2
    - six >=1.10.0
    - protobuf

test:
  imports:
    - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow
