#  docker build  -f  Dockerfile_conda492_py38_ubuntu20 -t houbenzhou/conda:dockerfile_conda492_py38_ubuntu20_20210916  .

FROM ubuntu:20.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get clean && apt-get -y update --fix-missing  && apt-get update && apt-get install -y --no-install-recommends \
        gnupg2 curl ca-certificates openjdk-8-jdk  build-essential \
        apt-utils \
        aria2 \
        wget \
        git \
        vim \
        libssl-dev \
        unzip \
        unrar  && \
        net-tools && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

ENV TINI_VERSION v0.16.1
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini

ENTRYPOINT [ "/usr/bin/tini", "--" ]
CMD [ "/bin/bash" ]
