#  docker build  -f  Dockerfile_copy_myconda -t houbenzhou/conda:copy_conda_tzb2  .
# docker run --gpus all -name test_tzb2_conda -itd -v /home:/home  tzb2_conda:base
# docker exec -it test_tzb2_conda /bin/bash
# docker rm test_tzb2_conda


FROM houbenzhou/conda:dockerfile_conda492_py38_ubuntu18_20210916

RUN rm -rf /opt/conda
ADD ./conda  /opt/conda/
ADD ./setconda.sh  /opt/

RUN cd /opt/ && sh setconda.sh
RUN echo "export PATH=$PATH:/opt/conda/bin" >> ~/.bashrc && source ~/.bashrc

