# ==================================================================
# module list
# ------------------------------------------------------------------
# ubuntu          18.04
# idesktop        10i
# iserver         10i

FROM dorowu/ubuntu-desktop-lxde-vnc:bionic
USER root
ENV SOFTWARE=/headless/Supermap/

COPY ./software/geoai/ $SOFTWARE/
# RUN cp $SOFTWARE/sources.list /etc/apt

# ==================================================================
# cuda base
# ------------------------------------------------------------------
RUN apt-get clean && apt-get -y update --fix-missing  && apt-get update && apt-get install -y --no-install-recommends \
        gnupg2 curl ca-certificates openjdk-8-jdk  build-essential \
        apt-utils \
        aria2 \
        wget \
        git \
        vim \
        libssl-dev \
        unzip \
        unrar  && \
    curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add - && \
    echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
    echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/lib/apt/lists/* -vf

ENV CUDA_VERSION 10.2.89
ENV CUDA_PKG_VERSION 10-2=$CUDA_VERSION-1

# For libraries in the cuda-compat-* package: https://docs.nvidia.com/cuda/eula/index.html#attachment-a
RUN apt-get update && aptitude install \
    cuda-cudart-$CUDA_PKG_VERSION \
    cuda-compat-10-2 \
    && ln -s cuda-10.2 /usr/local/cuda

# Required for nvidia-docker v1
RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=10.2 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441"


# ==================================================================
# cuda dev
# ------------------------------------------------------------------

ENV NCCL_VERSION 2.7.8

RUN apt-get update && aptitude install \
    cuda-nvml-dev-$CUDA_PKG_VERSION \
    cuda-command-line-tools-$CUDA_PKG_VERSION \
    cuda-nvprof-$CUDA_PKG_VERSION \
    cuda-npp-dev-$CUDA_PKG_VERSION \
    cuda-libraries-dev-$CUDA_PKG_VERSION \
    cuda-minimal-build-$CUDA_PKG_VERSION \
    libcublas-dev=10.2.2.89-1 \
    libnccl-dev=2.7.8-1+cuda10.2 \
    && apt-mark hold libnccl-dev

ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs


# ==================================================================
# cuda cudnn7
# ------------------------------------------------------------------
ENV CUDNN_VERSION 7.6.5.32

LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && aptitude install \
    libcudnn7=$CUDNN_VERSION-1+cuda10.2 \
    libcudnn7-dev=$CUDNN_VERSION-1+cuda10.2 \
    && apt-mark hold libcudnn7 && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/lib/apt/lists/* -vf



# ==================================================================
# start script
# ------------------------------------------------------------------
RUN rm -rf /root/.pip/ && \
    mkdir -p /root/.pip && \
    mkdir -p /headless/Supermap/ && \
    mkdir -p /opt/SuperMap/License/&& \
    mkdir -p /opt/SuperMap/iobjects/1010/ && \
    cp $SOFTWARE/pip.conf  /root/.pip/ && \
    cp $SOFTWARE/supermap_any_2020.lic9d  /opt/SuperMap/License/ && \
    cp -r $SOFTWARE/Bin  /opt/SuperMap/iobjects/1010/ && \
    cp $SOFTWARE/pycharm.desktop  /usr/share/applications

