# ==================================================================
# module list
# ------------------------------------------------------------------
# ubuntu          18.04
# idesktop        10i
# iserver         10i

FROM dorowu/ubuntu-desktop-lxde-vnc:bionic
USER root
ENV SOFTWARE=/headless/Supermap/

COPY ./software/geoai/ $SOFTWARE/
RUN cp $SOFTWARE/sources.list /etc/apt
# ==================================================================
# 支持中文
# ------------------------------------------------------------------
ENV LANG=zh_CN.utf8
RUN export LANG=$LANG
USER root

# ==================================================================
# software
# ------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
gnupg2 curl ca-certificates openjdk-8-jdk && \
    curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add - && \
    echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
    echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get purge --autoremove -y curl && \
rm -rf /var/lib/apt/lists/*

ENV CUDA_VERSION 10.2.89

ENV CUDA_PKG_VERSION 10-2=$CUDA_VERSION-1

# For libraries in the cuda-compat-* package: https://docs.nvidia.com/cuda/eula/index.html#attachment-a
RUN apt-get update && apt-get install -y --no-install-recommends \
        cuda-cudart-$CUDA_PKG_VERSION \
cuda-compat-10-2 && \
ln -s cuda-10.2 /usr/local/cuda && \
    rm -rf /var/lib/apt/lists/*

# Required for nvidia-docker v1
RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=10.2 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419"


RUN rm -rf /root/.pip/ && \
    mkdir -p /root/.pip && \
    mkdir -p /headless/Supermap/ && \
    mkdir -p /opt/SuperMap/License/&& \
    mkdir -p /opt/SuperMap/iobjects/1001/ && \
    cp $SOFTWARE/pip.conf  /root/.pip/ && \
    cp $SOFTWARE/supermap_any_2020.lic9d  /opt/SuperMap/License/ && \
    cp -r $SOFTWARE/Bin  /opt/SuperMap/iobjects/1001/ && \
    cp $SOFTWARE/pycharm.desktop  /usr/share/applications

# ==================================================================
# start script
# ------------------------------------------------------------------
EXPOSE 80
WORKDIR /root
ENV HOME=/home/ubuntu \
    SHELL=/bin/bash
HEALTHCHECK --interval=30s --timeout=5s CMD curl --fail http://127.0.0.1:6079/api/health
ENTRYPOINT ["/startup.sh"]
